name: Claude PR Creation
on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          allowed_tools: "View,Edit,Replace,DeleteFile,CreateFile,GlobTool,GrepTool,Bash(git status),Bash(git diff),Bash(git log),Bash(git show),Bash(git blame),Bash(git reflog),Bash(git stash list),Bash(git ls-files),Bash(git branch),Bash(git tag),Bash(git checkout),Bash(git add .),Bash(git commit -m \"Automated commit by Claude\"),Bash(git push origin HEAD),Bash(find . -name '*.py'),Bash(ls -la),NotebookEditCell,TaskOutput"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: "claude-sonnet-4-20250514"
